@apiURL = http://localhost:8080

@JWT = {{$dotenv JWT_TEST}}

GET {{apiURL}}/notes
Content-Type: application/json
Authorization: Bearer {{JWT}}

###

POST {{apiURL}}/notes
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
    "boardId": "670d401ca6e5a9c7b7237d94",
    "note": "Complete everything",
    "style": ""
}

###

PATCH {{apiURL}}/notes/6716098e5a3e81069d5b26e7
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
    "note": "Fix this thing",
    "style": ""
}

###

DELETE {{apiURL}}/notes/6716409b303c7833e5ee00e0
Content-Type: application/json
Authorization: Bearer {{JWT}}